import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/Header";
import PTransition from "@/components/PTransition";
// import ComponiesProvider from "@/context/ComponiesContext";
// import ShowInfoProvider from "@/context/ShowInfoContext";
import TotalContext from "@/context/TotalContext";

const vazirFont = localFont({
  src: "../fonts/Vazir.woff2",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={vazirFont.className}>
        <TotalContext>
          <Header />
          <PTransition>
            {children}
          </PTransition>
        </TotalContext>
      </body>
    </html>
  );
}
